# Required Vars:
# ${_libName}
# ${LIB_PUBLIC_HEADERS}
SET( LIB_NAME ${_libName} )

SET(INSTALL_INCDIR include)
SET(INSTALL_BINDIR bin)
IF(WIN32)
    SET(INSTALL_LIBDIR bin)
    SET(INSTALL_ARCHIVEDIR lib)
ELSE()
    SET(INSTALL_LIBDIR lib${LIB_POSTFIX})
    SET(INSTALL_ARCHIVEDIR lib${LIB_POSTFIX})
ENDIF()

SET(HEADERS_GROUP "Header Files")

SOURCE_GROUP(
    ${HEADERS_GROUP}
    FILES ${LIB_PUBLIC_HEADERS}
)

INSTALL(
    TARGETS ${LIB_NAME}
    EXPORT libprc-targets
    RUNTIME DESTINATION ${INSTALL_BINDIR} COMPONENT libprc
    LIBRARY DESTINATION ${INSTALL_LIBDIR} COMPONENT libprc
    ARCHIVE DESTINATION ${INSTALL_ARCHIVEDIR} COMPONENT libprc-dev
)
